PROMPT ====================================================
PROMPT      <<< SQLTools extract DDL utility V1.2 >>>      
PROMPT      USAGE: Run SQL Plus and input "start DO.sql"   
PROMPT ====================================================

spool DO.log

@@Types.sql
@@Table\CABINET.sql
@@Table\CARDIO_COMPANY.sql
@@Table\CARDIO_PARTNER.sql
@@Table\CARDIO_PARTNER_TYPE.sql
@@Table\CARDIO_PROJECT.sql
@@Table\CARDIO_ROLE.sql
@@Table\CARDIO_STORE.sql
@@Table\CARDIO_USER.sql
@@Table\CARDIO_USER_ROLES.sql
@@Table\CONTACTS.sql
@@Table\CONTACTS_DATA.sql
@@Table\CONTACT_TYPE.sql
@@Table\CPAP_TYPE.sql
@@Table\CUSHION_TYPE.sql
@@Table\DIVISION.sql
@@Table\DOCTORS_EXTERNAL.sql
@@Table\DOCTOR_ASSOC.sql
@@Table\DOCTOR_DIVISION.sql
@@Table\DOCTOR_POSITION.sql
@@Table\DOCTOR_PRIORITY.sql
@@Table\DOCTOR_RANK.sql
@@Table\DOCTOR_TYPE.sql
@@Table\DOCUMENT_STATUS.sql
@@Table\DOCUMENT_TYPE.sql
@@Table\EX_DOC_TYPE.sql
@@Table\MASK_SIZE.sql
@@Table\MASK_TYPE.sql
@@Table\OXYMAT_TYPE.sql
@@Table\PARTNER_ADDRESS.sql
@@Table\PARTNER_BANK_RECV.sql
@@Table\PARTNER_EMPLOYE.sql
@@Table\PARTNER_EMPLOYE_PHONE.sql
@@Table\PARTNER_EVENT.sql
@@Table\PARTNER_EVENT_ATTRS.sql
@@Table\PARTNER_EVENT_SUBJ.sql
@@Table\PARTNER_EVENT_TYPE.sql
@@Table\PARTNER_EVNT_ATTR_PAY_STAT.sql
@@Table\PARTNER_EVNT_CP_SUBJ.sql
@@Table\PATIENT.sql
@@Table\PATIENT_CALL.sql
@@Table\PATIENT_DOCUMENT.sql
@@Table\PATIENT_FEELING.sql
@@Table\PATIENT_PHONE.sql
@@Table\PATIENT_PHOTO.sql
@@Table\PF_THEME.sql
@@Table\POSITION.sql
@@Table\PROJECT_EQUIPMENT.sql
@@Table\PROJECT_EVENT.sql
@@Table\PROJECT_EVENT_ATTRS.sql
@@Table\PROJECT_PERSON.sql
@@Table\PROJECT_STATUS.sql
@@Table\PSG.sql
@@Table\PSG_ATTR_AD.sql
@@Table\PSG_ATTR_APNOE.sql
@@Table\PSG_ATTR_APNOE_TYPE.sql
@@Table\PSG_ATTR_BREATH_FREQ.sql
@@Table\PSG_ATTR_CPAP_BALANCE_PRM.sql
@@Table\PSG_ATTR_CPAP_CURR_PRESS.sql
@@Table\PSG_ATTR_CPAP_VENT_PRESS.sql
@@Table\PSG_ATTR_DETECTOR.sql
@@Table\PSG_ATTR_DETECTOR_TUNE.sql
@@Table\PSG_ATTR_ECG.sql
@@Table\PSG_ATTR_PULLS.sql
@@Table\PSG_ATTR_SNORING.sql
@@Table\PSG_ATTR_SP_O2.sql
@@Table\PSG_ATTR_TOILET_WAKE.sql
@@Table\PSG_RESULT.sql
@@Table\PSG_RESULT_AUTHOR.sql
@@Table\REF_INFO_SOURCE_TYPE.sql
@@Table\SEND_RANK.sql
@@Table\STORE_DOCUMENT.sql
@@Table\STORE_DOC_LINE.sql
@@Table\STORE_ITEM.sql
@@Table\STORE_ITEM_MODEL.sql
@@Table\STORE_ITEM_STATUS.sql
@@Table\STORE_ITEM_TYPE.sql
@@Table\STORE_ITEM_VENDOR.sql
@@Table\STORE_ITEM_VENDOR_TO_TYPE.sql
@@Table\TASK.sql
@@Table\TASK_EQUIPMENT.sql
@@Table\TASK_STATUS.sql
@@Table\TASK_STORE_ITEM.sql
@@Table\TASK_TYPE.sql
@@Table\TEL_TYPE.sql
@@Table\TMP_EQUQIPMENT.sql
@@Table\TMP_IMP_REFS1.sql
@@Table\UA_DISTRICT.sql
@@Table\UA_STATE.sql
@@Table\UA_TOWN.sql
@@Table\USER_EDUCATION.sql
@@Table\USER_FILES.sql
@@Table\USER_OCCUPATION.sql
@@Table\USER_PHONE.sql
@@Table\VIP_RANK.sql
@@Table\CARDIO_PARTNER~INX.sql
@@Table\CARDIO_PROJECT~INX.sql
@@Table\CARDIO_USER~INX.sql
@@Table\PARTNER_ADDRESS~INX.sql
@@Table\PARTNER_BANK_RECV~INX.sql
@@Table\PARTNER_EMPLOYE~INX.sql
@@Table\PARTNER_EMPLOYE_PHONE~INX.sql
@@Table\PARTNER_EVENT~INX.sql
@@Table\PARTNER_EVENT_ATTRS~INX.sql
@@Table\PATIENT_DOCUMENT~INX.sql
@@Table\PATIENT_PHOTO~INX.sql
@@Table\PROJECT_EQUIPMENT~INX.sql
@@Table\PROJECT_EVENT~INX.sql
@@Table\PROJECT_EVENT_ATTRS~INX.sql
@@Table\PROJECT_PERSON~INX.sql
@@Table\PSG~INX.sql
@@Table\PSG_ATTR_AD~INX.sql
@@Table\PSG_ATTR_APNOE~INX.sql
@@Table\PSG_ATTR_BREATH_FREQ~INX.sql
@@Table\PSG_ATTR_CPAP_BALANCE_PRM~INX.sql
@@Table\PSG_ATTR_CPAP_CURR_PRESS~INX.sql
@@Table\PSG_ATTR_CPAP_VENT_PRESS~INX.sql
@@Table\PSG_ATTR_DETECTOR_TUNE~INX.sql
@@Table\PSG_ATTR_ECG~INX.sql
@@Table\PSG_ATTR_PULLS~INX.sql
@@Table\PSG_ATTR_SNORING~INX.sql
@@Table\PSG_ATTR_SP_O2~INX.sql
@@Table\PSG_ATTR_TOILET_WAKE~INX.sql
@@Table\PSG_RESULT~INX.sql
@@Table\STORE_DOCUMENT~INX.sql
@@Table\STORE_DOC_LINE~INX.sql
@@Table\STORE_ITEM~INX.sql
@@Table\STORE_ITEM_MODEL~INX.sql
@@Table\TASK~INX.sql
@@Table\TASK_EQUIPMENT~INX.sql
@@Table\TASK_STORE_ITEM~INX.sql
@@Table\UA_DISTRICT~INX.sql
@@Table\UA_TOWN~INX.sql
@@Table\USER_EDUCATION~INX.sql
@@Table\USER_FILES~INX.sql
@@Table\USER_OCCUPATION~INX.sql
@@Table\USER_PHONE~INX.sql
@@Table\PATIENT~CHK.sql
@@Table\PSG_ATTR_AD~CHK.sql
@@Table\CABINET~UNQ.sql
@@Table\CARDIO_COMPANY~UNQ.sql
@@Table\CARDIO_PARTNER~UNQ.sql
@@Table\CARDIO_PARTNER_TYPE~UNQ.sql
@@Table\CARDIO_PROJECT~UNQ.sql
@@Table\CARDIO_ROLE~UNQ.sql
@@Table\CARDIO_STORE~UNQ.sql
@@Table\CARDIO_USER~UNQ.sql
@@Table\CARDIO_USER_ROLES~UNQ.sql
@@Table\CONTACTS~UNQ.sql
@@Table\CONTACTS_DATA~UNQ.sql
@@Table\CONTACT_TYPE~UNQ.sql
@@Table\CPAP_TYPE~UNQ.sql
@@Table\CUSHION_TYPE~UNQ.sql
@@Table\DIVISION~UNQ.sql
@@Table\DOCTORS_EXTERNAL~UNQ.sql
@@Table\DOCTOR_ASSOC~UNQ.sql
@@Table\DOCTOR_DIVISION~UNQ.sql
@@Table\DOCTOR_POSITION~UNQ.sql
@@Table\DOCTOR_PRIORITY~UNQ.sql
@@Table\DOCTOR_RANK~UNQ.sql
@@Table\DOCTOR_TYPE~UNQ.sql
@@Table\DOCUMENT_STATUS~UNQ.sql
@@Table\DOCUMENT_TYPE~UNQ.sql
@@Table\EX_DOC_TYPE~UNQ.sql
@@Table\MASK_SIZE~UNQ.sql
@@Table\MASK_TYPE~UNQ.sql
@@Table\OXYMAT_TYPE~UNQ.sql
@@Table\PARTNER_ADDRESS~UNQ.sql
@@Table\PARTNER_BANK_RECV~UNQ.sql
@@Table\PARTNER_EMPLOYE~UNQ.sql
@@Table\PARTNER_EMPLOYE_PHONE~UNQ.sql
@@Table\PARTNER_EVENT~UNQ.sql
@@Table\PARTNER_EVENT_ATTRS~UNQ.sql
@@Table\PARTNER_EVENT_SUBJ~UNQ.sql
@@Table\PARTNER_EVENT_TYPE~UNQ.sql
@@Table\PARTNER_EVNT_ATTR_PAY_STAT~UNQ.sql
@@Table\PARTNER_EVNT_CP_SUBJ~UNQ.sql
@@Table\PATIENT~UNQ.sql
@@Table\PATIENT_CALL~UNQ.sql
@@Table\PATIENT_DOCUMENT~UNQ.sql
@@Table\PATIENT_FEELING~UNQ.sql
@@Table\PATIENT_PHONE~UNQ.sql
@@Table\PATIENT_PHOTO~UNQ.sql
@@Table\PF_THEME~UNQ.sql
@@Table\POSITION~UNQ.sql
@@Table\PROJECT_EQUIPMENT~UNQ.sql
@@Table\PROJECT_EVENT~UNQ.sql
@@Table\PROJECT_EVENT_ATTRS~UNQ.sql
@@Table\PROJECT_PERSON~UNQ.sql
@@Table\PROJECT_STATUS~UNQ.sql
@@Table\PSG~UNQ.sql
@@Table\PSG_ATTR_AD~UNQ.sql
@@Table\PSG_ATTR_APNOE~UNQ.sql
@@Table\PSG_ATTR_APNOE_TYPE~UNQ.sql
@@Table\PSG_ATTR_BREATH_FREQ~UNQ.sql
@@Table\PSG_ATTR_CPAP_BALANCE_PRM~UNQ.sql
@@Table\PSG_ATTR_CPAP_CURR_PRESS~UNQ.sql
@@Table\PSG_ATTR_CPAP_VENT_PRESS~UNQ.sql
@@Table\PSG_ATTR_DETECTOR~UNQ.sql
@@Table\PSG_ATTR_DETECTOR_TUNE~UNQ.sql
@@Table\PSG_ATTR_ECG~UNQ.sql
@@Table\PSG_ATTR_PULLS~UNQ.sql
@@Table\PSG_ATTR_SNORING~UNQ.sql
@@Table\PSG_ATTR_SP_O2~UNQ.sql
@@Table\PSG_ATTR_TOILET_WAKE~UNQ.sql
@@Table\PSG_RESULT~UNQ.sql
@@Table\PSG_RESULT_AUTHOR~UNQ.sql
@@Table\REF_INFO_SOURCE_TYPE~UNQ.sql
@@Table\SEND_RANK~UNQ.sql
@@Table\STORE_DOCUMENT~UNQ.sql
@@Table\STORE_DOC_LINE~UNQ.sql
@@Table\STORE_ITEM~UNQ.sql
@@Table\STORE_ITEM_MODEL~UNQ.sql
@@Table\STORE_ITEM_STATUS~UNQ.sql
@@Table\STORE_ITEM_TYPE~UNQ.sql
@@Table\STORE_ITEM_VENDOR~UNQ.sql
@@Table\STORE_ITEM_VENDOR_TO_TYPE~UNQ.sql
@@Table\TASK~UNQ.sql
@@Table\TASK_EQUIPMENT~UNQ.sql
@@Table\TASK_STATUS~UNQ.sql
@@Table\TASK_TYPE~UNQ.sql
@@Table\TEL_TYPE~UNQ.sql
@@Table\UA_DISTRICT~UNQ.sql
@@Table\UA_STATE~UNQ.sql
@@Table\UA_TOWN~UNQ.sql
@@Table\USER_EDUCATION~UNQ.sql
@@Table\USER_FILES~UNQ.sql
@@Table\USER_OCCUPATION~UNQ.sql
@@Table\USER_PHONE~UNQ.sql
@@Table\VIP_RANK~UNQ.sql
@@Table\CARDIO_PARTNER~FK.sql
@@Table\CARDIO_PROJECT~FK.sql
@@Table\CARDIO_USER~FK.sql
@@Table\CARDIO_USER_ROLES~FK.sql
@@Table\CONTACTS_DATA~FK.sql
@@Table\DOCTORS_EXTERNAL~FK.sql
@@Table\PARTNER_ADDRESS~FK.sql
@@Table\PARTNER_BANK_RECV~FK.sql
@@Table\PARTNER_EMPLOYE~FK.sql
@@Table\PARTNER_EMPLOYE_PHONE~FK.sql
@@Table\PARTNER_EVENT~FK.sql
@@Table\PARTNER_EVENT_ATTRS~FK.sql
@@Table\PATIENT~FK.sql
@@Table\PATIENT_CALL~FK.sql
@@Table\PATIENT_DOCUMENT~FK.sql
@@Table\PATIENT_PHONE~FK.sql
@@Table\PATIENT_PHOTO~FK.sql
@@Table\PROJECT_EQUIPMENT~FK.sql
@@Table\PROJECT_EVENT~FK.sql
@@Table\PROJECT_EVENT_ATTRS~FK.sql
@@Table\PROJECT_PERSON~FK.sql
@@Table\PSG~FK.sql
@@Table\PSG_ATTR_AD~FK.sql
@@Table\PSG_ATTR_APNOE~FK.sql
@@Table\PSG_ATTR_BREATH_FREQ~FK.sql
@@Table\PSG_ATTR_CPAP_BALANCE_PRM~FK.sql
@@Table\PSG_ATTR_CPAP_CURR_PRESS~FK.sql
@@Table\PSG_ATTR_CPAP_VENT_PRESS~FK.sql
@@Table\PSG_ATTR_DETECTOR_TUNE~FK.sql
@@Table\PSG_ATTR_ECG~FK.sql
@@Table\PSG_ATTR_PULLS~FK.sql
@@Table\PSG_ATTR_SNORING~FK.sql
@@Table\PSG_ATTR_SP_O2~FK.sql
@@Table\PSG_ATTR_TOILET_WAKE~FK.sql
@@Table\PSG_RESULT~FK.sql
@@Table\STORE_DOCUMENT~FK.sql
@@Table\STORE_DOC_LINE~FK.sql
@@Table\STORE_ITEM~FK.sql
@@Table\STORE_ITEM_MODEL~FK.sql
@@Table\STORE_ITEM_VENDOR_TO_TYPE~FK.sql
@@Table\TASK~FK.sql
@@Table\TASK_EQUIPMENT~FK.sql
@@Table\TASK_STORE_ITEM~FK.sql
@@Table\UA_DISTRICT~FK.sql
@@Table\UA_TOWN~FK.sql
@@Table\USER_EDUCATION~FK.sql
@@Table\USER_FILES~FK.sql
@@Table\USER_OCCUPATION~FK.sql
@@Table\USER_PHONE~FK.sql
@@Sequence\CABINET_SEQ.sql
@@Sequence\CARDIO_COMPANY_SEQ.sql
@@Sequence\CARDIO_PARTNER_SEQ.sql
@@Sequence\CARDIO_PROJECT_SEQ.sql
@@Sequence\CARDIO_ROLE_SEQ.sql
@@Sequence\CARDIO_USER_ROLES_SEQ.sql
@@Sequence\CARDIO_USER_SEQ.sql
@@Sequence\CONTACTS_DATA_SEQ.sql
@@Sequence\CONTACTS_SEQ.sql
@@Sequence\CONTACT_TYPE_SEQ.sql
@@Sequence\CPAP_TYPE_SEQ.sql
@@Sequence\CUSHION_TYPE_SEQ.sql
@@Sequence\DIVISION_SEQ.sql
@@Sequence\DOCTORS_EXTERNAL_SEQ.sql
@@Sequence\DOCTOR_ASSOC_SEQ.sql
@@Sequence\DOCTOR_DIVISION_SEQ.sql
@@Sequence\DOCTOR_POSITION_SEQ.sql
@@Sequence\DOCTOR_RANK_SEQ.sql
@@Sequence\DOCTOR_TYPE_SEQ.sql
@@Sequence\EX_DOC_TYPE_SEQ.sql
@@Sequence\MASK_SIZE_SEQ.sql
@@Sequence\MASK_TYPE_SEQ.sql
@@Sequence\OXYMAT_TYPE_SEQ.sql
@@Sequence\PARTNER_ADDRESS_SEQ.sql
@@Sequence\PARTNER_BANK_RECV_SEQ.sql
@@Sequence\PARTNER_EMPLOYE_PHONE_SEQ.sql
@@Sequence\PARTNER_EMPLOYE_SEQ.sql
@@Sequence\PARTNER_EVENT_SEQ.sql
@@Sequence\PARTNER_EVENT_SUBJ_SEQ.sql
@@Sequence\PARTNER_EVENT_TYPE_SEQ.sql
@@Sequence\PATIENT_CALL_SEQ.sql
@@Sequence\PATIENT_DOCUMENT_SEQ.sql
@@Sequence\PATIENT_PHONE_SEQ.sql
@@Sequence\PATIENT_PHOTO_SEQ.sql
@@Sequence\PATIENT_SEQ.sql
@@Sequence\POSITION_SEQ.sql
@@Sequence\PROJECT_EQUIPMENT_SEQ.sql
@@Sequence\PROJECT_EVENT_SEQ.sql
@@Sequence\PROJECT_PERSON_SEQ.sql
@@Sequence\PROJECT_SEQ.sql
@@Sequence\PSG_ATTR_AD_SEQ.sql
@@Sequence\PSG_ATTR_APNOE_SEQ.sql
@@Sequence\PSG_ATTR_BREATH_FREQ_SEQ.sql
@@Sequence\PSG_ATTR_CPAP_BALANCE_PRM_SEQ.sql
@@Sequence\PSG_ATTR_CPAP_CURR_PRESS_SEQ.sql
@@Sequence\PSG_ATTR_CPAP_PRESSUE_SEQ.sql
@@Sequence\PSG_ATTR_DETECTOR_SEQ.sql
@@Sequence\PSG_ATTR_DETECTOR_TUNE_SEQ.sql
@@Sequence\PSG_ATTR_ECG_SEQ.sql
@@Sequence\PSG_ATTR_PULLS_SEQ.sql
@@Sequence\PSG_ATTR_SNORING_SEQ.sql
@@Sequence\PSG_ATTR_SP_O2_SEQ.sql
@@Sequence\PSG_ATTR_TOILET_WAKE_SEQ.sql
@@Sequence\PSG_RESULT_AUTHOR_SEQ.sql
@@Sequence\PSG_RESULT_SEQ.sql
@@Sequence\PSG_SEQ.sql
@@Sequence\REF_INFO_SOURCE_TYPE_SEQ.sql
@@Sequence\SEND_RANK_SEQ.sql
@@Sequence\STORE_DOCUMENT_SEQ.sql
@@Sequence\STORE_DOC_LINE_SEQ.sql
@@Sequence\STORE_ITEM_MODEL_SEQ.sql
@@Sequence\STORE_ITEM_SEQ.sql
@@Sequence\STORE_ITEM_TYPE_SEQ.sql
@@Sequence\STORE_ITEM_VENDOR_SEQ.sql
@@Sequence\TASK_EQUIPMENT_SEQ.sql
@@Sequence\TASK_SEQ.sql
@@Sequence\TASK_STORE_ITEM_SEQ.sql
@@Sequence\TEL_TYPE_SEQ.sql
@@Sequence\TMP_EIMP_TOWN_SEQ.sql
@@Sequence\UA_DISTRICT_SEQ.sql
@@Sequence\UA_STATE_SEQ.sql
@@Sequence\UA_TOWN_SEQ.sql
@@Sequence\USER_EDUCATION_SEQ.sql
@@Sequence\USER_FILES_SEQ.sql
@@Sequence\USER_OCCUPATION_SEQ.sql
@@Sequence\USER_PHONE_SEQ.sql
@@Sequence\VIP_RANK_SEQ.sql
@@Function\MD5.sql
@@Function\MD5_RAW.sql
@@Package\REP_UTL.sql
@@View\USER_GROUPS_VIEW.sql
@@PackageBody\REP_UTL.sql

EXEC Dbms_Utility.compile_schema(USER, FALSE);

spool off
exit
